dna = "AGGGGTCTGGCACAAACGGCTAACTGGCACTGTAAGACCGGCGGAATCTTCTGAAGCACCTAGCTCCGTGGTTCCAACTGAATAACCATCAGGTAGACTGTAGATTACAAGGCACCAGTGCGACATACGACTCAATACTAAGTCTGGTCGCGGATGTGACGTTTGTATAGAAATCGTACTGACGACGCTGGTTGAGAATGGACACGACTGGCAGCCCAAGCTTGTATGGCGGGGCGCGGCGTAACAACACTCCGCTGGAGCCAGCTTGGATACTCCGCCCAGTGGCGACTTACCCGATTCCTGTCGAAGTTCTAGGATATATTCGCGGGCATAACTTTTCCTTGGAACATCACCCACCTATACTCTGATCACCATAAAAAAGCAGGCTATTTGTTGGTACACACACTTGTCAGCGAAATGCTCCGACACGGAGATCGCGAAAAATATACAACAAGCCTGGGTGATCCTACGGCGGGAAAAATCTCGAATGTGAAGGTGATAATTACGTTCTAGAAACAATGGCCCTGAATTTTTTCCTAGGCTATGTGAGAGCGATGGAGTTTCCTATCTTACTCTAAGGGTAGGATAATGATGATATACCTTTACTAACGCCATCGTGCTCCCCATAGGCGAGTTATTATCTGCGAACGACGTCTGCGACCCGCCATAATCTCTAGCACACACATAGGAGCGTAAAGATGCATGCGCGGCACCGGAGAAAACCCGAGGGGAAGTAATACCGAAGTGTGGAAGCTTAAGAATTATAGCATAAGCAACGCAGGGATGACAGGCGAGGCGTTGAAATTCTCAGTTCCCGGCC"
new_dna = ""

for c in dna:
    if c == "A":
        new_dna += "T"
    elif c == "T":
        new_dna += "A"
    elif c == "C":
        new_dna += "G"
    elif c == "G":
        new_dna += "C"

print(new_dna[::-1])